[package]
name = "rust_ffmpeg_example"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
ffmpeg-next = "6.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
bincode = "1.3"
base64 = "0.13"      # Для кодирования кадров в base64